version: "3.5"
services:
  chatbot:
    container_name: fraqbot
    restart: always
    image: drewpearce/trd-fraqbot
    # build: fraqbot/
    env_file: .env
    volumes:
      - "$HOME/logs:/tmp/logs"
      - "./config.yaml:/usr/src/app/config.yaml"
      - ./fraqbot/Local/coins_tx:/usr/src/app/Local/coins_tx
    networks:
      legobot:
        aliases:
          - legobot

networks:
  legobot:
    name: legobot
    external: false
