connectors:
  Slack:
    enabled: true
    path: Legobot.Connectors.Slack.Slack
    kwargs:
      token: <a Slack API token>
helpEnabled: true
legos:
  AshokCoin:
    enabled: true
    path: Local.coins.Coins # Import path to the Lego Class
    kwargs:
      acl: # acl restricts Lego interaction to only whitelist/blacklist. Usefor for testing.
        whitelist:
          - <a Slack user ID>
      name: AshokCoin
      starting_value: 200
      admins:
        - <a Slack user ID>
      triggers:
        - "!ashokcoin"
        - "!ak"
      pool_excludes:
        - <a Slack bot ID> # Keeps fraqbot from getting paid from the pool.
  